# -*- mode: ruby -*-
# vi: set ft=ruby :


# defining some variables.  File is so small not really needed.
$local_chef_stuff_path = "C:\\vagrantboxes/chef"
$local_cookbooks_path = $local_chef_stuff_path + "/cookbooks/"
$local_roles_path = $local_chef_stuff_path +  "/roles/"	
$local_nodes_path = $local_chef_stuff_path +  "/nodes/"

$local_node_role = "apache-php"	# Role exists in  $local_roles_path
$local_node_name = "apache-php" # Node exists in  $local_nodes_path

$chef_version = '12.19.33'

$virtual_machine_base = "bento/oracle-7.3"

$vm_sync_folder = "/data/html"
$local_sync_folder = "C:\\data/www_root"

# for this box I map 8080 on the Local machine to port 80 on the virtual machine for use by the www
# for this box I map 2222 on the Local machine to port 22 on the virtual machine for use by the ssh

# the www document_root is defined / overridden in the role file


Vagrant.configure("2") do |config|

	config.vm.box = $virtual_machine_base

	# change add ports
	config.vm.network "forwarded_port", guest: 8080, host: 80, host_ip: "127.0.0.1", id: 'www'
	
	# This prob stays the same
	config.vm.network "forwarded_port", guest: 22, host: 2222, host_ip: "127.0.0.1", id: 'ssh'

	# ensure the vagrant box has the sync directory created
	config.vm.provision "shell" do |s|
		s.inline = "mkdir -p " + $vm_sync_folder
	end  

	config.vm.provision "chef_solo" do |chef|
		chef.version = $chef_version
		chef.cookbooks_path = $local_cookbooks_path
		chef.roles_path = $local_roles_path	
		chef.nodes_path = $local_nodes_path		
		chef.add_role $local_node_role
		chef.node_name = $local_node_name
	end

	# mount the sync folder
	config.vm.synced_folder $local_sync_folder, $vm_sync_folder, id: "www-data",
		owner: "vagrant",
		group: "vagrant",
		mount_options: ["dmode=777", "fmode=777"]   

	# vim is not on base box so install it after box is running
	config.vm.provision "shell" do |s|
		s.inline = "yum install -y vim"
	end  
  
end
