source 'https://supermarket.chef.io'
source :chef_server

# If you need to use Local cookbook path and not one on chef server
# because local cookbook has modifications that are not uploaded yet
# Example:  cookbook 'tl_app', path: 'C:\\Cookbooks/tl_app'

cookbook 'tl_fedora', '0.1.1'